"""FLORA — Literature Mining (SCOUT) page."""

import streamlit as st


def render():
    st.title("Literature Mining")
    st.caption("KNOWLEDGE / ADMIN")
    st.markdown(
        "Describe the research you are looking for. "
        "FLORA will plan search queries, search OpenAlex, and filter results "
        "for relevance — keeping only papers that genuinely match."
    )

    # Show memory status
    try:
        from flora_scout.scout import _load_known_dois
        known = _load_known_dois()
        if known:
            st.info(
                f"Memory: **{len(known)} papers already in project** "
                f"(from extraction results, records, and miner history). "
                f"Scout will skip these automatically."
            )
    except Exception:
        pass

    with st.form("scout_form"):
        description = st.text_area(
            "Describe the research you want to find",
            height=130,
            placeholder=(
                "e.g. I am looking for papers that report the synthesis of organic "
                "molecules using continuous flow chemistry. Specifically photocatalytic "
                "or thermal reactions performed in flow reactors (coil reactors, "
                "microreactors) with real synthetic outcomes. NOT reviews, NOT "
                "biological microfluidics, NOT analytical flow injection analysis."
            ),
        )
        c1, c2, c3 = st.columns(3)
        with c1:
            n_papers = st.number_input("Target papers", 10, 200, value=50)
        with c2:
            year_from = st.number_input("From year", 2010, 2026, value=2015)
        with c3:
            snowball = st.checkbox("Citation snowballing", value=False,
                                   help="Also fetch papers citing the top results")
        submitted = st.form_submit_button("Start Mining", type="primary",
                                          use_container_width=True)

    if not submitted or not description.strip():
        _show_tips()
        return

    progress = st.progress(0, text="Initializing...")
    log_area  = st.empty()
    stats_area = st.empty()

    def cb(p, msg):
        progress.progress(min(p, 1.0), text=msg)
        log_area.caption(msg)

    try:
        from flora_scout.scout import Scout

        # Show the query plan before starting
        with st.spinner("Planning search strategy..."):
            from flora_scout.scout import QueryPlanner
            planner = QueryPlanner()
            plan = planner.plan(description)

        with st.expander("Search strategy (generated by LLM)", expanded=True):
            c1, c2 = st.columns(2)
            with c1:
                st.markdown("**Search queries:**")
                for q in plan.get("primary_queries", []):
                    st.markdown(f"- `{q}`")
                st.markdown("**Required terms (at least one):**")
                for t in plan.get("required_terms", []):
                    st.markdown(f"- `{t}`")
            with c2:
                st.markdown("**Exclusion terms:**")
                for t in plan.get("exclusion_terms", []):
                    st.markdown(f"- `{t}`")
                st.markdown("**Relevance criteria:**")
                st.caption(plan.get("relevance_description", ""))

        scout = Scout(
            description=description,
            n_target=n_papers,
            year_from=year_from,
            snowball=snowball,
            progress_callback=cb,
        )
        # Inject the already-computed plan to avoid a second LLM call
        # (Scout will call planner internally, but this is fine — small cost)
        results = scout.run()

        progress.progress(1.0, text="Done")
        st.success(
            f"Mining complete — **{len(results)} relevant papers** found."
        )

        import pandas as pd
        df = pd.DataFrame(results)

        # Show relevance distribution
        if "relevance_score" in df.columns:
            import plotly.graph_objects as go
            fig = go.Figure(go.Histogram(
                x=df["relevance_score"],
                nbinsx=10,
                marker_color="#3b82f6",
            ))
            fig.update_layout(
                xaxis_title="Relevance score (0-10)",
                yaxis_title="Number of papers",
                height=200,
                margin=dict(l=30, r=10, t=20, b=40),
                template="plotly_white",
            )
            st.plotly_chart(fig, use_container_width=True)

        # Main table
        display_cols = [c for c in [
            "doi", "title", "year", "n_citations",
            "relevance_score", "relevance_reason", "score"
        ] if c in df.columns]
        st.dataframe(df[display_cols], use_container_width=True, hide_index=True)

        c1, c2 = st.columns(2)
        with c1:
            st.download_button(
                "Download results (CSV)",
                df.to_csv(index=False), "scout_results.csv", "text/csv",
                use_container_width=True,
            )
        with c2:
            # DOI-only list for PRISM pipeline
            doi_list = "\n".join(df["doi"].dropna().tolist())
            st.download_button(
                "Download DOI list (TXT)",
                doi_list, "doi_list.txt", "text/plain",
                use_container_width=True,
            )

    except Exception as e:
        from components.error_card import render_error
        render_error(e, "SCOUT")


def _show_tips():
    with st.expander("Tips for better results", expanded=False):
        st.markdown("""
**Be specific about what you want:**
> *"Papers reporting photocatalytic C-C bond formation reactions conducted in
> continuous flow reactors, with experimental yields reported. Must include
> flow chemistry setup details."*

**Tell it what to exclude:**
> *"NOT reviews. NOT papers about biological flow. NOT microfluidic diagnostic
> chips. Only papers with actual synthesis outcomes."*

**Mention key concepts:**
> *"Ir or Ru photocatalysis, radical reactions, FEP coil reactor,
> residence time, continuous manufacturing"*

The more specific your description, the more loyal the results will be.
FLORA generates 5 different search angles and filters each result for relevance.
        """)
