"""Publication figures from recorded chemistry, equipment and NMR yields.

Chemical depictions use RDKit; no reaction or result is generated by a model.
"""
from pathlib import Path
import csv
import io
import json
import sys

sys.path.append('/tmp/flowpilot-figure-tools')
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, Circle
import numpy as np
from PIL import Image
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors
from rdkit.Chem.Draw import rdMolDraw2D
import cairosvg

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'manuscript/Submission/overhaul_20260930'
FIG = OUT / 'figures'
OLD = ROOT / 'manuscript/Submission/revision_20260929/figures'
ICONS = ROOT / 'flora_design/visualizer/icons'
INK, TEAL, BLUE, GRAY = '#202b31', '#177d78', '#426e9c', '#64717b'
plt.rcParams.update({'font.family': 'Liberation Sans', 'font.size': 11,
                     'pdf.fonttype': 42, 'svg.fonttype': 'none'})

STRUCTURES = {
    '1a': ('COc1ccc(SC[Si](C)(C)C)cc1', 'C11H18OSSi'),
    '3a': ('COc1ccc(SCCCC#N)cc1', 'C11H13NOS'),
    '4a': ('COc1ccc(S(=O)CCCC#N)cc1', 'C11H13NO2S'),
    '1b': ('O=C(O)c1cc(C)c([N+](=O)[O-])cc1', 'C8H7NO4'),
    'thioester': ('O=C(Sc2ccccn2)c1cc(C)c([N+](=O)[O-])cc1', 'C13H10N2O3S'),
    '3b': ('O=C(NCc2ccccc2)c1cc(C)c([N+](=O)[O-])cc1', 'C15H14N2O3'),
}
YIELDS = [
    {'figure': 5, 'label': 'Literature flow', 'yield_pct': 90, 'method': '1H NMR', 'source': 'Park et al., Table 4, entry 5', 'doi': '10.1039/D4GC05769D', 'grouped': False},
    {'figure': 5, 'label': 'FlowPilot sets 1 / 3', 'yield_pct': 97, 'method': '1H NMR', 'source': 'KHU supplied result table, Figure S2, entry 3', 'doi': '', 'grouped': True},
    {'figure': 5, 'label': 'FlowPilot set 2', 'yield_pct': 98, 'method': '1H NMR', 'source': 'KHU supplied result table, Figure S2, entry 4', 'doi': '', 'grouped': False},
    {'figure': 6, 'label': 'Literature batch', 'yield_pct': 98, 'method': '1H NMR', 'source': 'Saunders et al., Table 1, entry 5', 'doi': '10.1021/acssuschemeng.5c00914', 'grouped': False},
    {'figure': 6, 'label': 'FlowPilot set 1', 'yield_pct': 86, 'method': '1H NMR', 'source': 'KHU supplied result table, Figure S4, entry 3', 'doi': '', 'grouped': False},
    {'figure': 6, 'label': 'FlowPilot sets 2 / 3', 'yield_pct': 68, 'method': '1H NMR', 'source': 'KHU supplied result table, Figure S4, entry 4', 'doi': '', 'grouped': True},
]


def molecules():
    result = {}
    for key, (smiles, formula) in STRUCTURES.items():
        mol = Chem.MolFromSmiles(smiles)
        actual = rdMolDescriptors.CalcMolFormula(mol)
        assert actual == formula, (key, actual, formula)
        draw = rdMolDraw2D.MolDraw2DSVG(600, 300)
        opts = draw.drawOptions()
        opts.useBWAtomPalette()
        opts.bondLineWidth = 2.6
        opts.minFontSize = 24
        opts.maxFontSize = 28
        opts.padding = .08
        draw.DrawMolecule(mol)
        draw.FinishDrawing()
        svg = draw.GetDrawingText()
        (FIG / f'structure_{key}.svg').write_text(svg)
        png = cairosvg.svg2png(bytestring=svg.encode(), output_width=1800, output_height=900)
        (FIG / f'structure_{key}.png').write_bytes(png)
        result[key] = {'smiles': Chem.MolToSmiles(mol), 'formula': actual}
    (OUT / 'chemical_structure_audit.json').write_text(json.dumps(result, indent=2) + '\n')


class Canvas:
    def __init__(self, height=7.25):
        self.width, self.height = 7.2, height
        self.fig = plt.figure(figsize=(self.width, self.height))
        self.ax = self.fig.add_axes([0, 0, 1, 1])
        self.ax.set(xlim=(0, self.width), ylim=(height, 0))
        self.ax.axis('off')
        self.labels = []

    def text(self, x, y, value, size=11, bold=False, color=INK, ha='left'):
        item = self.ax.text(x, y, value, fontsize=size, fontweight='bold' if bold else 'normal',
                            color=color, ha=ha, va='top', linespacing=1.25)
        self.labels.append(item)
        return item

    def panel(self, letter, y, title):
        self.text(.10, y, letter, 14, True)
        self.text(.45, y + .015, title, 12, True)

    def image(self, path, x, y, w, h):
        im = Image.open(path)
        scale = min(w / im.width, h / im.height)
        iw, ih = im.width * scale, im.height * scale
        ax = self.fig.add_axes([(x + (w-iw)/2)/self.width, 1-(y+(h+ih)/2)/self.height,
                               iw/self.width, ih/self.height], zorder=3)
        ax.imshow(im)
        ax.axis('off')

    def arrow(self, x1, y1, x2, y2, color=INK):
        self.ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle='-|>',
                                          mutation_scale=11, lw=1.15, color=color))

    def rule(self, y):
        self.ax.plot([.1, 7.1], [y, y], color='#d9dfe1', lw=.8)

    def save(self, name):
        self.fig.canvas.draw()
        renderer = self.fig.canvas.get_renderer()
        issues = []
        bounds = [(x.get_text(), x.get_window_extent(renderer)) for x in self.labels]
        for i, (label, box) in enumerate(bounds):
            if box.x0 < -1 or box.y0 < -1 or box.x1 > self.fig.bbox.width + 1 or box.y1 > self.fig.bbox.height + 1:
                issues.append('Outside: ' + label)
            for label2, box2 in bounds[i+1:]:
                if min(box.x1, box2.x1)-max(box.x0, box2.x0)>1 and min(box.y1,box2.y1)-max(box.y0,box2.y0)>1:
                    issues.append('Overlap: ' + label + ' / ' + label2)
        (OUT / f'{name}_layout_audit.json').write_text(json.dumps({'issues': issues, 'labels': len(bounds)}, indent=2))
        assert not issues, issues
        for suffix in ('svg', 'pdf', 'png'):
            self.fig.savefig(FIG / f'{name}.{suffix}', dpi=600, facecolor='white')
        self.fig.savefig(FIG / f'{name}_preview.png', dpi=160, facecolor='white')
        plt.close(self.fig)


def reaction(p, number):
    p.panel('a', .05, 'Two-stage photoredox sequence' if number == 5 else 'Telescoped activation and amidation')
    keys = ['1a', '3a', '4a'] if number == 5 else ['1b', 'thioester', '3b']
    names = ['Precursor 1a', 'Sulfide 3a', 'Sulfoxide 4a'] if number == 5 else ['Acid 1b', '2-Pyridyl thioester', 'Amide 3b']
    for x, key, label in zip([.08, 2.76, 5.15], keys, names):
        p.image(FIG / f'structure_{key}.png', x, .75, 1.96, .78)
        p.text(x + .98, 1.55, label, 10.5, ha='center')
    for left, right in [(2.04, 2.76), (4.72, 5.15)]:
        p.arrow(left, 1.14, right, 1.14)
    if number == 5:
        p.text(2.35, .43, 'Giese\naddition', 9.5, ha='center')
        p.text(4.92, .43, 'Oxidation', 9.5, ha='center')
        p.text(.13, 1.81, 'Acrylonitrile (2 equiv), Ir photocatalyst (0.5 mol%); EtOH / pH 9 buffer (5:1).', 10)
    else:
        p.text(2.37, .43, 'DPDTC\nDMAP', 9.5, ha='center')
        p.text(4.95, .43, 'Benzylamine', 9, ha='center')
        p.text(.13, 1.81, 'DPDTC (1.05 equiv), DMAP (10 mol%), benzylamine (1.05 equiv); 2-MeTHF.', 10)
    p.rule(2.12)


def process(p, number):
    p.panel('b', 2.28, 'Connected configuration implemented at KHU')
    # Schematic summary of the documented path, not a piping/safety drawing.
    y = 3.43
    for a, b in [(.9, 1.65), (2.30, 3.11), (3.25, 4.04), (4.70, 5.22), (5.78, 6.3)]:
        p.arrow(a, y, b, y)
    p.image(ICONS / '_pump_generic.png', .18, 3.12, .69, .62)
    p.image(ICONS / ('photoreactor.png' if number == 5 else 'coil_reactor.png'), 1.63, 3.09, .72, .68)
    p.image(ICONS / ('photoreactor.png' if number == 5 else 'coil_reactor.png'), 4.02, 3.09, .72, .68)
    p.image(ICONS / 'bpr.png', 5.21, 3.16, .56, .55)
    p.image(ICONS / 'vial.png', 6.31, 3.12, .54, .61)
    p.ax.add_patch(Circle((3.18, y), .055, facecolor=INK, edgecolor=INK))
    p.arrow(3.18, 2.93, 3.18, y-.045, BLUE)
    p.text(3.18, 3.56, 'T-mixer', 9, ha='center')
    if number == 5:
        p.text(3.18, 2.67, 'O$_2$ via MFC: 0.090 mL/min*', 10, color=BLUE, ha='center')
        data = [(.53, 'Feed A\n0.020 mL/min'), (1.99, 'R1: 2 or 5 mL\nPFA / UV-150\n450 nm'), (4.39, 'R2: 20 mL\nFEP / strip LED\n~448 nm'), (5.49, '7 bar\ncartridge'), (6.58, 'Collect')]
        p.text(.14, 4.45, '25 ± 1 °C  |  2 mL sample loop  |  O$_2$ introduced only after R1', 10, color=TEAL)
    else:
        p.text(3.18, 2.63, 'Feed B: benzylamine, 2.10 M\n0.040 or 0.070 mL/min', 10, color=BLUE, ha='center')
        data = [(.53, 'Feed A\n0.160 or 0.280\nmL/min'), (1.99, 'R1: 5 or 10 mL\nETFE\n95 °C'), (4.39, 'R2: 5 mL\nETFE\n95 °C'), (5.49, '7 bar\ncartridge'), (6.58, 'Collect')]
        p.text(.14, 4.45, 'Two E-series pump channels  |  2 mL sample loop  |  No intermediate isolation', 10, color=TEAL)
    for x, label in data:
        p.text(x, 3.82, label, 9.8, ha='center')
    p.rule(4.76)


def results(p, number):
    p.panel('c', 4.93, 'Operating points and yield')
    headers = ['KHU set(s)', 'R1 time', 'R2 time*' if number == 5 else 'R2 time', 'Pressure']
    xs = [.14, 1.48, 2.37, 3.33]
    for x, label in zip(xs, headers):
        p.text(x, 5.43, label, 9.5, True)
    for x, label in zip(xs[1:], ['min', 'min', 'bar']):
        p.text(x, 5.66, label, 9.2, color=GRAY)
    values = [['1 / 3', '100', '181.8', '5.1–5.4'], ['2', '250', '181.8', '5.2–5.6']] if number == 5 else [['1', '31.25', '25.00', '5.2–5.3'], ['2 / 3', '35.71', '14.29', '5.5–5.8']]
    for y, row in zip([6.02, 6.46], values):
        for x, label in zip(xs, row):
            p.text(x, y, label, 10.3)
    p.ax.plot([.14, 4.12], [5.92, 5.92], color='#c9d2d6', lw=.7)
    # Labeled horizontal measurements, not repeated/triplicated observations.
    p.text(4.53, 5.41, 'Yield (%)', 10.5, True)
    rows = [r for r in YIELDS if r['figure'] == number]
    for i, row in enumerate(rows):
        y = 5.82 + i*.43
        color = GRAY if i == 0 else TEAL
        p.text(4.52, y-.07, row['label'].replace('FlowPilot ', ''), 9.5, color=color)
        start, end = 6.02, 6.70
        x = start + row['yield_pct']/100*(end-start)
        p.ax.plot([start,end], [y+.07,y+.07], color='#e4e8e9', lw=3, solid_capstyle='round')
        p.ax.plot([start,x], [y+.07,y+.07], color=color, lw=3, solid_capstyle='round')
        p.ax.plot(x, y+.07, 'o', markersize=5, color=color, mfc='white' if i == 0 else color)
        p.text(7.04, y-.02, str(row['yield_pct']), 10.5, True, color, ha='right')
    p.text(.14, 6.96, '*R2 is an inlet/STP time index, not operating-pressure residence time.' if number == 5 else 'Stage times use V$_1$/Q$_A$ and V$_2$/(Q$_A$ + Q$_B$), respectively.', 9)


def illumination():
    p = Canvas(7.4)
    source = OLD.parent / 'sources/khu'
    items = [('a', 'Batch: two MR16 5 W lamps', None),
             ('b', 'R1: Vapourtec 450 nm LED', 'image6.png'),
             ('c', 'R2: blue strip LED', 'image8.png')]
    for i, (letter, title, filename) in enumerate(items):
        y = .05+i*2.43
        p.panel(letter, y, title)
        # Compose the original supplied photographs/traces without altering data.
        if filename:
            p.image(source/filename, .14, y+.44, 6.90, 1.83)
        else:
            p.image(source/'image1.png', .14, y+.44, 1.45, 1.83)
            p.image(source/'image2.png', 1.77, y+.44, 5.27, 1.83)
    p.save('figureS17_irradiation_sources')


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    molecules()
    for number in (5, 6):
        p = Canvas()
        reaction(p, number); process(p, number); results(p, number)
        p.save(f'figure{number}_redesigned')
    illumination()
    with (OUT / 'yield_comparison.csv').open('w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(YIELDS[0])); w.writeheader(); w.writerows(YIELDS)
    (OUT / 'excluded_yield_bases.json').write_text(json.dumps([
        {'figure': 5, 'context': 'Literature batch', 'yield_pct': 95, 'method': 'isolated', 'source': 'Park et al., Table 1, entry 13, footnote b'},
        {'figure': 6, 'context': 'Literature flow', 'yield_pct': 97, 'method': 'isolated', 'source': 'Saunders et al., Scope: Amide Formation; Scheme 4'},
    ], indent=2) + '\n')
    print('Built verified structures, Figures 5-6, irradiation composite and yield provenance.')


if __name__ == '__main__':
    main()
